[tool.poetry]
name = "cluedin"
version = "4.0.0"
description = "CluedIn Python SDK"
authors = ["Roman Klimenko <roman@klimenko.dk>", "Martin Hyldahl"]
readme = "cluedin/README.md"
license = "MIT"
keywords = ["cluedin", "mdm", "master data management"]
maintainers = ["CluedIn"]
homepage = "https://github.com/CluedIn-io/CluedIn.SDK.Py"
repository = "https://github.com/CluedIn-io/CluedIn.SDK.Py"

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.32.3"

[tool.poetry.group.test.dependencies]
pytest = ">=8.3.5,<10.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
